Numpy : 
- Dimensions are called axes

In [2]:
import numpy as np
x = [[0,1,2], [3,4,5], [6,7,8]]
arr = np.array(x)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

2
(3, 3)
9
int64
8


In [5]:
#Ones and Zeros
import numpy as np
arr = np.zeros((5,5))
print(arr)
print("---"*20)
arr1 = np.ones((5,5))
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
------------------------------------------------------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
