Numpy : 
- Dimensions are called axes

In [2]:
import numpy as np
x = [[0,1,2], [3,4,5], [6,7,8]]
arr = np.array(x)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

2
(3, 3)
9
int64
8


In [5]:
#Ones and Zeros
import numpy as np
arr = np.zeros((5,5))
print(arr)
print("---"*20)
arr1 = np.ones((5,5))
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
------------------------------------------------------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [11]:
##In copy(), The contents are physically stored in different location. 
##if the value of items in arr1 is changed, arr2 remains unchanged
import numpy as np
arr1 = np.array([1,2,3])
arr2 = arr1.copy()
print(arr2)
arr1[0] = 15
print(arr1)
print(arr2)

[1 2 3]
[15  2  3]
[1 2 3]


In [17]:
import numpy as np
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
import numpy as np
arr = np.linspace(0,20,5)
arr

array([ 0.,  5., 10., 15., 20.])

In [19]:
import numpy as np
arr = np.arange(4)
print(arr)
print(arr+4)
print(arr*2)

[0 1 2 3]
[4 5 6 7]
[0 2 4 6]


In [21]:
import numpy as np
arr = np.arange(4)
arr1 = np.arange(4,8)
print(arr)
print(arr1)
print(arr+arr1)
print(arr-arr1)
print(arr*arr1)

[0 1 2 3]
[4 5 6 7]
[ 4  6  8 10]
[-4 -4 -4 -4]
[ 0  5 12 21]


In [26]:
import numpy as np
arr = np.arange(0,9)
arr1 = np.ones((3,3))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr1)
print(arr2.ndim)
print(arr2.shape)
print(arr*arr1)

[0 1 2 3 4 5 6 7 8]
1
(9,)
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1
(3,)


ValueError: operands could not be broadcast together with shapes (9,) (3,3) 

In [37]:
import numpy as np
arr = np.arange(0,9).reshape(3,-1)
arr1 = np.ones((3,3))
print("*****arr attributes*****")
print(arr)
print(arr.ndim)
print(arr.shape)

print("*****arr2 attributes *****")

print(arr1)
print(arr2.ndim)
print(arr2.shape)

print("*****dot product for c *****")
c = arr*arr1
c1 = np.dot(arr,arr1)
print(c)
print(c1)

print("*****c attributes *****")
print(c.ndim)
print(c.shape)

*****arr attributes*****
[[0 1 2]
 [3 4 5]
 [6 7 8]]
2
(3, 3)
*****arr2 attributes *****
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1
(3,)
*****dot product for c *****
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
[[ 3.  3.  3.]
 [12. 12. 12.]
 [21. 21. 21.]]
*****c attributes *****
2
(3, 3)


In [38]:
import numpy as np
arr = np.sqrt([1,4,9])
print(arr)

[1. 2. 3.]


In [41]:
## Aggregate functions
import numpy as np
a = np.array([1,2,3,4,5])
print(a.sum())
print(a.mean())
print(a.max())
print(a.min())
print(a.std())

15
3.0
5
1
1.4142135623730951
